typedef unsigned char byte;
void xor(byte *a, byte *b, int i);
void Sub_Bytes_one(byte a[4][4]);
void Sub_Bytes_two(byte *a, int i);
void KeyCore(byte *a, int i);
void KeyExp(const byte *a, byte *b);
void ShiftRows(byte a[4][4]);
void MixCols(byte a[4][4]);
void AddRoundKey(byte a[4][4], byte *b);
void copy(byte a[4][4], byte b[4][4]);
void encrypt(byte a[4][4], const byte *key, byte b[4][4]);
void AddRoundKey_inv(byte a[4][4], byte *b);
void MixColInv(byte a[4][4]);
void ShiftRows_inv(byte a[4][4]);
void SubBytes_inv(byte a[4][4]);
void decrypt(byte a[4][4], const byte *key, byte b[4][4]);
void set(byte a[4][4]);
